---
title: "Documentación/guías del team data"
date: Última actualización `r format(Sys.time(), '%d %b %Y')`
output: 
  html_document:
    self_contained: yes
    includes:
      in_header: header.html
    theme: flatly
    highlight: haddock
    # code_folding: show
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: true
    keep_md: false
    keep_tex: false 
    css: "style.css" 
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, dpi=300)
```

## Introducción

Este documento contiene guías/referencias para la organización de la información utilizada por el equipo de data. También contiene información de buenas prácticas para la elaboración de estudios/análisis enfocados en asegurar un gasto público eficiente y tomar decisiones basadas en evidencia.

El presente documento contiene enlaces y referencias para los conceptos utilizados en la construcción de la carpeta de data que se encuentra en la siguiente ruta del Disco B "B:\OneDrive - Ministerio de Educación\unidad_B\0. Data".

## Escribiendo código que otros puedan entender

El buen código es facil de entender y ejecutar por otros. Es importante internalizar que el código es un resultado en sí mismo y no solo un medio para un fin, por lo tanto, debe ser fácil de leer para cualquier integrante.

El primer paso es generar un "master script", un master es un script que se puede utilizar para ejecutar todo el código de un proyecto. Cualquier miembro del equipo debería poder ejecutar este script y otros scripts del proyecto cambiando solo la ruta del archivo del directorio en una línea de código en el master script.

Puedes ver un ejemplo aquí. (ejemplo)



### Organización de proyectos/análisis

Generalmente, dentro de una carpeta de proyecto, tenemos una subcarpeta de análisis, donde guardamos las bases de datos, los scripts y otra documentación. Dentro de la subcarpeta "análisis", tenemos:

- Un archivo .Rproj para el proyecto. (Esto se puede crear en RStudio, con Archivo> Nuevo proyecto).
  - Hay que tener en cuenta que es recomendable abrir el Proyecto en RStudio antes de trabajar (ve a "Proyecto" en la esquina superior derecha de RStudio), aquí el paquete `here` funcionará para rutas de archivo relativas (solo aplicabe para proyectos en R).
- data: contiene las bases de datos utilizadas en el análisis.
  - raw: contiene las bases de datos raw o "crudas" utilizadas en el análisis.
  - clean: contiene las bases de datos limpias
- documentacion: la documentación sobre los datos va en esta carpeta.
- ouput - los output del código van en esta carpeta
   - figuras - subcarpeta para figuras
   - tablas - subcarpeta para tablas
- scripts - el código va en esta carpeta
   - programas: una subcarpeta que contiene funciones llamadas por los scripts de análisis (si corresponde)

### Control de versiones

### GitHub
Github es una herramienta importante para mantener el control de versiones y con fines de asegurar replicabilidad. Aquí mostramos un workflow básico para generar un proyecto en GitHub

1. Para clonar un repositorio de github existente, descarga e instala GitHub Desktop en tu PC. Inicia sesión en GitHub Desktop con tu usuario Github.Haz click en el botón verde Code que se muestra arriba de la lista de archivos en este repositorio, haz click en la opción Open with GitHub Desktop.
2. Para crear un nuevo repositorio, ve a GitHub.com y haz click en "Crear repositorio", elije un nombre para el repositorio y una descripción. Luego puedes clonarlo utilizando los pasos anteriores.
3. Copia los archivos de tu proyecto en la carpeta sincronizada. Luego abre GitHub Desktop y sincroniza con `git push` add . Tus documentos ahora están en GitHub y ya puedes compartirlos!.

Sin embargo, hay ocasiones en las que nos encontramos con conflictos Un conflicto es un evento que ocurre cuando Git no puede resolver automáticamente las diferencias en el código entre dos push Por ejemplo, si un colaborador edita un fragmento de código, prepara, confirma e impulsa un cambio, y luego intentamos subir cambios para el mismo fragmento de código, se encontrará con un conflicto. En estos casos se debe editar manualmente el código y eliminar las líneas de código que no desee y los caracteres especiales que Git agregó en el archivo. Después de eso, se puede preparar, confirmar y enviar los archivos sin conflictos.

## Otros conceptos

- Data en formato tidy: Datos en formato tidy proporcionan una forma estandarizada para trabajar con datos, puedes leer mas en este articulo de Towards Data Science: https://towardsdatascience.com/what-is-tidy-data-d58bb9ad2458 En general, la data en formato tidy tiene que cumplir con las siguientes reglas:
  - Cada variable es una columna
  - Cada observacion es una fila

Usaremos el formato tidy para convertir las tablas de datos “raw” o crudas en tablas de datos clean.

- GitHub: Github nos permite establecer un proceso de control de versiones. El control de versiones es una parte importante de la administración de datos del equipo. Sigue las instrucciones para crearte una cuenta y tenerla instalada. Ya tienes una cuenta en GitHub.com? Si no, ve a: https://github.com/join e inscríbete. Envíame tu usuario de GitHub por discord (bmora) o al correo analistaup29@minedu.gob.pe. Descarga e instala Github Desktop en tu PC: https://desktop.github.com/. Inicia sesión en GitHub Desktop con tu usuario Github. Una vez que me envies tu usuario de GitHub, te invitaré al repositorio de datos de UPP.

Se utilizará GitHub para administrar el código de la carpeta Data. Puedes leer más en la diapositiva de capacitación: https://mineduperu-my.sharepoint.com/:p:/g/personal/analistaup29_minedu_gob_pe/ERp3WjX76zFJpMLf8_41zJ8BAc6HST6HCmXJ0T8-Mrrmig?e=LutwZF. También puedes revisar las diapositivas del BM en su curso de introducción a GitHub en el siguiente enlace: https://osf.io/5ugkv/

3. Guía de estilo para el código: Es importante que todos manejemos una manera de escribir código que sea transparente y entendible, por tal motivo puedes leer desde la página 178 de este libro para aprender a documentar código y otras buenas prácticas en Stata: https://openknowledge.worldbank.org/handle/10986/35594.